# Generated by Django 5.2.9 on 2025-12-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('bookmark_collections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                (
                    'url_type',
                    models.CharField(
                        choices=[
                            ('website', 'Website'),
                            ('book', 'Book'),
                            ('article', 'Article'),
                            ('music', 'Music'),
                            ('video', 'Video'),
                        ],
                        default='website',
                        max_length=32,
                    ),
                ),
                ('image', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'collections',
                    models.ManyToManyField(blank=True, related_name='bookmarks', to='bookmark_collections.collection'),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
