# Generated by Django 4.2.8 on 2023-12-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
